#!/bin/bash



function newline() {
    [ "$1" ] && local length="$1" || local length=1
    for (( i = 0; i < length; i++ )); do
        # CPU Power Saving
        if [ 100 -le "$i" ]; then
            break
        fi

        echo ''
    done
}

function *() {
    [ "$*" ] && local length="$*" || local length=16
    local asterisks=''

    # Type: String
    if ! expr "$length" : '[0-9]*' > /dev/null ; then
        length="${#length}"
    fi

    for (( i = 0; i < length; i++ )); do
        # CPU Power Saving
        if [ 100 -le "$i" ]; then
            break
        fi

        asterisks="${asterisks}*"
    done

    echo "$asterisks"
}

function *echo() {
    local asterisks="$(\* "$*")"

    newline
    echo "$asterisks"
    echo "$*"
    echo "$asterisks"
}
